# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('likes', models.CharField(max_length=20)),
                ('comments_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HoleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, default='yanjin', max_length=20)),
                ('text', models.TextField(default="Oh! There's no text......")),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('github', models.URLField(blank=True, default='https://github.com/yan-jin')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(default="Oh! There's no description......")),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('img', models.ManyToManyField(blank=True, to='blogapp.Pictures')),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='comments',
            field=models.ManyToManyField(blank=True, to='blogapp.HoleComment'),
        ),
    ]
