# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='date',
        ),
        migrations.AddField(
            model_name='holecomment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
